/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#4e4637",
        "on-tertiary": "#003910",
        "on-secondary-fixed": "#001c38",
        "on-primary-fixed": "#261900",
        "on-background": "#dfe2eb",
        "on-primary-fixed-variant": "#5d4200",
        "surface-bright": "#353940",
        "error": "#ffb4ab",
        "primary-container": "#f0c060",
        "outline": "#9b8f7d",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#74dd7e",
        "surface-container-highest": "#31353c",
        "on-surface-variant": "#d2c5b1",
        "on-tertiary-fixed": "#002106",
        "on-secondary-fixed-variant": "#004882",
        "secondary": "#a2c9ff",
        "surface-variant": "#31353c",
        "secondary-fixed": "#d3e4ff",
        "on-primary": "#412d00",
        "surface-dim": "#10141a",
        "on-secondary-container": "#f0f4ff",
        "surface-tint": "#efbf5f",
        "on-primary-container": "#6c4e00",
        "tertiary-container": "#74dd7e",
        "surface-container-high": "#262a31",
        "inverse-on-surface": "#2d3137",
        "tertiary": "#90fa98",
        "background": "#10141a",
        "primary": "#ffdfa6",
        "surface-container": "#1c2026",
        "secondary-container": "#0071c7",
        "on-secondary": "#00315c",
        "primary-fixed-dim": "#efbf5f",
        "on-tertiary-container": "#006120",
        "primary-fixed": "#ffdea4",
        "on-surface": "#dfe2eb",
        "surface": "#10141a",
        "surface-container-lowest": "#0a0e14",
        "secondary-fixed-dim": "#a2c9ff",
        "inverse-primary": "#7b5900",
        "on-tertiary-fixed-variant": "#00531b",
        "surface-container-low": "#181c22",
        "inverse-surface": "#dfe2eb",
        "on-error": "#690005",
        "tertiary-fixed": "#90fa97",
        "error-container": "#93000a",

        // Mapeamentos antigos pro código não quebrar inteiramente de uma vez:
        'bg': '#10141a',
        'surface-2': '#1c2026',
        'border': '#4e4637',
        'text': '#dfe2eb',
        'text-dim': '#d2c5b1',
        'text-mute': '#9b8f7d',
        'gold': '#f0c060',
        'green': '#74dd7e',
        'blue': '#a2c9ff',
        'red': '#ffb4ab',
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "md": "24px",
        "border-width": "3px",
        "base": "4px",
        "xs": "8px",
        "lg": "40px",
        "xl": "64px",
        "shadow-offset": "4px",
        "container-max": "1100px",
        "sm": "16px"
      },
      fontFamily: {
        "label-caps": ["JetBrains Mono", "monospace"],
        "code": ["JetBrains Mono", "monospace"],
        "h1": ["Space Grotesk", "sans-serif"],
        "h3": ["Space Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "h2": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        // Fallbacks
        "mono": ["JetBrains Mono", "monospace"],
        "sans": ["Hanken Grotesk", "sans-serif"],
        "cinzel": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "label-caps": ["14px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "code": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "h1": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "h3": ["24px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "h2": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
